export const TOTAL_SCENES = 12;
export const SEC_PER_SCENE = 10;

export const TOD_DATA = {
	morning: {
		label: "Morning / Pagi",
		emoji: "🌅",
		lighting:
			"warm golden sunrise light, low angle rays, mist on valley floor, fresh crisp air",
		sky: "pale gold and amber horizon, soft pink-peach sky gradient, light mist lingering",
		timeRange: '04:30–09:00',
	},
	day: {
		label: "Midday / Siang",
		emoji: "☀️",
		lighting:
			"bright high sun, vivid colors, maximum saturation, clear visibility",
		sky: "deep blue sky, white cumulus clouds, strong light, sharp shadows",
		timeRange: '09:00–14:00',
	},
	afternoon: {
		label: "Golden Hour / Sore",
		emoji: "🌇",
		lighting:
			"magical golden hour warmth, long horizontal rays, everything bathed in amber-orange",
		sky: "stunning orange-pink-purple sunset gradient, dramatic clouds lit from below",
		timeRange: '14:00–19:00',
	},
	night: {
		label: "Dusk & Night / Malam",
		emoji: "🌙",
		lighting:
			"blue hour twilight, cool blue-violet light, soft shadow, stars appearing",
		sky: "deep indigo fading to black, first stars visible, crescent moon low",
		timeRange: '19:00–04:30',
	},
} as const;

export const SCENE_TYPES = {
	mountain: "🏔️ Pegunungan",
	hills: "🌄 Bukit Hijau",
	river: "🌊 Sungai Mengalir",
	ricefield: "🌾 Pesawahan",
	lavender: "💜 Kebun Bunga",
	forest: "🌲 Hutan Lebat",
	lake: "🏞️ Danau Tenang",
	village: "🏘️ Pedesaan",
	cliff: "⛰️ Tebing Pantai",
	vineyard: "🍇 Kebun Anggur",
	waterfall: "💧 Air Terjun",
	tundra: "🌿 Padang Terbuka",
} as const;

export const VISUAL_STYLE_LABELS = {
	cinematic: "Cinematic",
	"semi-cinematic": "Semi-Cinematic",
	"cinematic-realistic": "Cinematic Realistic",
	realistic: "Realistic",
	"hyper-realistic": "Hyper Realistic",
} as const;

export const VISUAL_STYLE_HINTS = {
	cinematic:
		"strong cinematic lighting, dramatic composition, gentle film grain, shallow depth of field where appropriate",
	"semi-cinematic":
		"balanced cinematic look, clean composition, soft contrast, relaxing music video polish",
	"cinematic-realistic":
		"photorealistic baseline with cinematic framing and color polish, natural textures",
	realistic:
		"natural documentary realism, neutral grading, minimal stylization, true-to-life colors",
	"hyper-realistic":
		"ultra photoreal, micro-detail textures, crisp clarity, high dynamic range realism",
} as const;

export const DEFAULT_TYPES = [
	"mountain",
	"hills",
	"river",
	"ricefield",
	"lavender",
	"forest",
	"lake",
	"village",
	"cliff",
	"vineyard",
	"waterfall",
	"tundra",
] as const;

export const OPTIONS = {
	natSpot: [
		"Mountain range — vast snow-capped peaks with valley below",
		"Rolling green hills — gentle undulating countryside pastures",
		"Flowing river — crystal clear water rushing over smooth stones",
		"Terraced rice fields — emerald green paddies in layers",
		"Lavender fields — endless purple blooms in soft breeze",
		"Alpine meadow — wildflowers among rocky peaks",
		"Dense forest — ancient trees with dappled light filtering",
		"Coastal cliffs — dramatic rocky shores meeting sea",
		"Peaceful lake — glassy water reflecting sky and mountains",
		"Waterfall — cascading white water into natural pool",
		"Vineyard landscape — neat rows of vines across gentle hills",
		"Rural village — traditional cottages with flower gardens",
		"Sunflower field — bright yellow sea under open sky",
		"Misty valley — morning fog rolling between green hills",
		"Autumn forest — fiery orange and gold canopy from above",
		"Tulip fields — geometric patterns of vivid color blocks",
	],
	natWater: [
		"gentle stream — water flowing over mossy rocks, soft babble",
		"wide river bend — slow peaceful meander through valley",
		"mountain waterfall — forceful cascade, mist rising below",
		"glassy lake reflection — perfect mirror of sky and peaks",
		"rice paddy irrigation channels — water slowly filling terraces",
		"coastal waves — rhythmic waves breaking on pebble shore",
		"no water element — pure land and sky this scene",
		"morning dew — tiny droplets on grass and leaves close-up",
		"river rapids — white water between boulders, energetic flow",
	],
	natVegetation: [
		"lush green grass meadow — vibrant emerald, thick and dense",
		"mixed deciduous forest — oak, beech, birch in full canopy",
		"pine forest — dark green conifers covering mountain slopes",
		"wildflower meadow — chamomile, poppy, cornflower scattered",
		"manicured hedgerows — English countryside garden walls",
		"olive groves — silver-green leaves, gnarled ancient trunks",
		"bamboo grove — swaying green stalks, zen atmosphere",
		"wheat fields — golden grain swaying in gentle wind",
		"tulip and bulb fields — Netherlands-style flat colorful geometry",
		"alpine edelweiss and heather — rugged mountain flora",
	],
	natTerrain: [
		"dramatic high mountain peaks — rugged glacial terrain",
		"gentle rolling hills — soft curves, pastoral farmland",
		"flat fertile plains — wide horizon, open sky dominant",
		"deep canyon valley — steep forested walls, river below",
		"coastal headland — cliffs meeting the sea dramatically",
		"lake district — multiple water bodies between green hills",
		"volcanic highland — dark basalt, unique dramatic landscape",
		"forested plateau — elevated flat land above clouds",
	],

	locCountry: [
		"Switzerland — Swiss Alps, Grindelwald, Lauterbrunnen valley",
		"Greenland — Arctic tundra, glaciers, midnight sun",
		"Netherlands — tulip fields, windmills, flat polder landscape",
		"Austria — Hallstatt, Tyrolean Alps, alpine lakes",
		"Norway — fjords, dramatic waterfalls, rugged coastline",
		"Iceland — volcanic landscape, waterfalls, aurora views",
		"Scotland — Highland moors, lochs, dramatic moody skies",
		"Tuscany Italy — rolling hills, cypress trees, vineyards",
		"Bavaria Germany — Neuschwanstein foothills, Alpine meadows",
		"Slovenia — Lake Bled, Julian Alps, pristine wilderness",
		"Czech Bohemian Countryside — rolling fields, medieval charm",
		"French Alps — Mont Blanc region, alpine villages",
		"Faroe Islands — dramatic cliffs, grass-roofed houses",
		"Spanish Pyrenees — dramatic mountain border scenery",
		"Polish Tatra Mountains — beautiful alpine national park",
		"Croatian Plitvice — cascading lakes, turquoise water",
	],
	locSetting: [
		"open mountain valley — panoramic 270° views, no buildings",
		"traditional alpine village — wooden chalets, flower boxes",
		"working farm — livestock, barns, cultivated fields",
		"remote wilderness — no human structures visible",
		"monastery / historic site — ancient buildings in nature",
		"hiking trail viewpoint — natural clearing, distant peaks",
		"riverside meadow — flat ground next to flowing water",
		"hilltop panorama — 360° view over landscape below",
	],
	locWeather: [
		"perfect clear day — vivid blue sky, crisp air, excellent visibility",
		"soft overcast — diffused light, no harsh shadows, moody grey",
		"light mist / fog — romantic haze softening distant hills",
		"after rain — glistening wet surfaces, fresh clean atmosphere",
		"light breeze — grasses and flowers gently swaying",
		"early spring — fresh greens, patches of last snow on peaks",
		"high summer — lush maximum green, warm golden light",
		"early autumn — hints of orange beginning in forest canopy",
		"winter scene — snow-covered, clean white, frozen details",
	],
	locPalette: [
		"emerald greens and sapphire blue — lush summer richness",
		"soft pastels — muted sage, dusty rose, pale sky blue",
		"golden earth tones — wheat yellows, amber, warm ochres",
		"cool Nordic tones — silver grey, pale green, muted blue",
		"vivid technicolor — saturated greens, bright wildflowers",
		"autumn fire — burnt orange, crimson, golden yellow",
		"winter monochrome — white snow, bare dark trees, grey sky",
		"lavender purple sea — Provence-inspired field tones",
	],

	aniBirds: [
		"birds of prey soaring — eagle or hawk riding thermals overhead",
		"flock of small birds — murmuration swirling across sky",
		"white swans — gliding on still lake surface, serene",
		"songbirds perched — chirping on nearby branches, tiny details",
		"storks nesting — large nest on chimney or tree",
		"ducks and geese — paddling on river or lake edge",
		"no birds — clear uninterrupted sky this scene",
		"heron standing still — patient fishing in shallow water",
		"colorful finches and robins — hopping on ground or fence",
	],
	aniLand: [
		"sheep grazing — fluffy white flock dotting green hillside",
		"mountain goats — sure-footed on rocky alpine terrain",
		"cows in meadow — black and white dairy cows grazing",
		"horses running free — mane flowing, galloping across field",
		"deer at forest edge — alert, elegant, ears perked",
		"rabbits in meadow — small brown rabbits nibbling grass",
		"no land animals — pure nature scenery this scene",
		"highland cattle — long-haired Scottish cattle iconic look",
		"goats with bells — Swiss alpine goats, gentle bell sounds",
	],
	aniInsects: [
		"butterflies — colorful wings on wildflowers, close drone hover",
		"bees on flowers — buzzing around lavender or wildflowers",
		"dragonfly over water — hovering above stream surface",
		"fireflies — tiny lights appearing in dusky meadow scene",
		"no insects visible — scene focuses on wider landscape",
		"ladybirds on leaves — tiny red details on green foliage",
	],
	aniWater: [
		"no water animals visible this scene",
		"salmon jumping upstream — dramatic splash in river",
		"fish visible through clear water — drone looks straight down",
		"ducks — group of ducks drifting on calm river",
		"frogs at pond edge — subtle movement in reeds",
		"otters playing — playful movement along riverbank",
	],

	visComposition: [
		"pure lush vegetation only — wall-to-wall green, no rocks, no water",
		"pure water element — river, lake or stream fills the visual",
		"pure rocky terrain — boulders, stone, dramatic geology",
		"mixed flora and water — stream winding through meadow",
		"mixed all elements — vegetation, rock, water beautifully combined",
		"sky dominant — dramatic cloudscape, landscape in lower third",
		"forest canopy — treetops from above, drone perspective",
		"flat pattern — tulip rows, rice terraces, geometric beauty",
	],
	visFlowers: [
		"wildflower mix — poppies, daisies, cornflowers, natural spread",
		"lavender fields — rows of purple extending to horizon",
		"tulip carpet — vivid red yellow pink geometric Dutch fields",
		"alpine edelweiss — delicate white flowers, mountain setting",
		"cherry blossom — soft pink petals, Japanese-European spring",
		"sunflower field — giant yellow heads following the sun",
		"no close flower detail — wide landscape this scene",
		"heather moorland — purple-pink low scrub on hillside",
	],
	visRocks: [
		"no prominent rocks — soft grassy scene, smooth terrain",
		"mossy river boulders — rounded stones with green coat",
		"dramatic cliff face — vertical rock exposed and powerful",
		"scattered fieldstones — natural rocky highland landscape",
		"mountain scree — loose talus slopes above treeline",
		"ancient stone walls — hand-laid pastoral boundary walls",
		"glacial erratic boulders — large isolated rocks in field",
		"limestone pavement — flat geometric natural rock floor",
	],
	visSky: [
		"perfect blue sky — minimal clouds, vibrant clean blue",
		"dramatic cumulus clouds — towering white billows, deep blue",
		"wispy cirrus — high thin ice clouds, serene atmosphere",
		"golden hour gradient — orange pink purple at horizon",
		"moody overcast — dramatic grey, diffused atmospheric light",
		"fast-moving clouds — dynamic movement with blue sky breaks",
		"sunrise colors — deep magenta bleeding into soft gold",
		"starry night sky — clear night, milky way visible",
		"aurora borealis — green curtains of northern lights",
	],

	lightMain: [
		"golden hour sunrise — first warm rays raking across landscape",
		"bright midday sun — high contrast, vivid saturated colors",
		"soft morning light — gentle diffused pre-noon warmth",
		"golden hour sunset — magical warm orange glow everywhere",
		"blue hour dusk — cool blue twilight just after sunset",
		"overcast soft light — clouds as giant softbox, no shadows",
		"backlit contre-jour — sun behind subject, halo and rim light",
		"moonlit night — silver blue cool moonlight on landscape",
		"dramatic storm light — dark clouds with single sunbeam shaft",
	],
	lightFx: [
		"god rays / light shafts — sun beams through trees or clouds",
		"lens flare — natural warm flare from direct sun angle",
		"water sparkle — light dancing and glittering on water surface",
		"dew shimmer — morning light catching moisture on grass",
		"shadow play — long dramatic shadows of trees and hills",
		"no special fx — clean cinematic natural light only",
		"mist diffusion — atmospheric haze softening all light",
		"rainbow — partial or full rainbow arc after light rain",
		"snow sparkle — crystalline glitter on fresh white snow",
	],
	lightColor: [
		"warm gold and amber — sunrise / sunset warmth",
		"cool blue and silver — morning, overcast or moonlight",
		"vivid green saturation — lush summer midday full spectrum",
		"soft pink and peach — dawn light, gentle pastel tones",
		"neutral white — bright cloudy, balanced color temperature",
		"purple and violet — dusk twilight, atmospheric depth",
		"orange and crimson — dramatic sunset intensely saturated",
		"silver and white — snow scene, winter color palette",
	],
	lightShadow: [
		"long soft shadows — low sun angle, painting texture on ground",
		"no visible shadows — overcast flat lighting, smooth surfaces",
		"dappled shade — light and shadow from forest canopy",
		"high contrast — deep shadows beside bright highlights",
		"soft rolling shadows — clouds passing over landscape",
		"reflection shadows — shadows on water surface distorted",
	],

	camMove: [
		"slow forward push — drone glides forward revealing landscape ahead",
		"rising reveal — drone climbs slowly, landscape expanding below",
		"wide banking arc — drone sweeps in curved orbit around subject",
		"descending approach — drone dips lower toward water or meadow",
		"lateral dolly slide — horizontal drift parallel to mountain range",
		"slow spiral ascent — rising while rotating for 360° panorama",
		"pull-back reveal — drone retreats to expose wider context",
		"bird's-eye top-down — drone directly overhead, looking straight down",
		"low-level skim — drone skims just above treetops or water",
		"following river course — drone traces the water flow path",
	],
	camAngle: [
		"45° angle down — classic drone angle, depth and horizon visible",
		"near horizontal — drone eye-level with treetops, epic panoramic",
		"straight down 90° — abstract geometric top-down view",
		"tilting from ground to sky — camera tilts up during move",
		"low oblique — just above ground level, intimate landscape",
		"high oblique — steep downward angle from great height",
	],
	camLens: [
		"ultra wide angle — vast sweeping view, sense of scale and space",
		"wide angle — standard cinematic drone wide perspective",
		"slight telephoto compression — stacking effect on landscape layers",
		"medium focal — balanced natural-eye perspective from altitude",
	],
	camSpeed: [
		"ultra-slow cinematic — barely perceptible movement, meditative",
		"slow and graceful — gentle relaxing pace, peaceful",
		"moderate smooth — confident steady movement, flowing",
		"slightly faster reveal — satisfying sweep with energy",
	],

	elemWind: [
		"gentle breeze — grasses and flowers softly swaying, peaceful",
		"strong wind — wheat fields rippling in dramatic waves",
		"no wind — perfectly still, mirror reflections possible",
		"occasional gusts — intermittent movement, natural variation",
		"leaves falling — gentle autumn leaf drift in still air",
		"snow drifting — light powder snow blowing off peaks",
	],
	elemHuman: [
		"no human elements — pure untouched nature",
		"distant farmhouse — tiny cottage far on hillside, scale reference",
		"old wooden fence — rustic fence line through meadow",
		"narrow country road — winding path through landscape",
		"stone bridge — ancient arch bridge over stream",
		"windmill — traditional Dutch or rural windmill rotating",
		"lone figure walking — tiny silhouette in vast landscape",
		"hay bales — golden cylinders dotting harvest fields",
	],
	elemAtmo: [
		"crystal clear air — maximum visibility, vivid colors",
		"gentle morning mist — thin haze hugging valley floor",
		"rolling fog — thick atmospheric cloud bank in distance",
		"heat shimmer — distant vibration in summer heat",
		"golden dust particles — fine particles catching low sun",
		"petals floating — cherry blossom or flower petals drifting",
		"pollen haze — golden pollen cloud over meadow",
		"rain veil — distant rainfall visible as grey curtain",
	],
	elemSeason: [
		"peak spring — fresh light greens, blossoms, new growth everywhere",
		"early summer — maximum lush green, vivid and full",
		"late summer — rich saturated greens, full bloom",
		"early autumn — hints of gold and rust entering canopy",
		"peak autumn — full foliage color, spectacular reds and golds",
		"late autumn — bare branches, last leaves, muted tones",
		"winter — snow-covered, pure white, minimal color",
		"early spring — first green shoots, last patches of snow",
	],

	styMood: [
		"deeply peaceful — serene, meditative, stress-releasing",
		"uplifting and joyful — bright, positive, feel-good warmth",
		"nostalgic and reflective — bittersweet longing, memories",
		"awe-inspiring grandeur — scale and majesty, breathtaking",
		"intimate and gentle — close and soft, like a warm embrace",
		"mysterious and ethereal — dreamlike, otherworldly beauty",
		"energizing and fresh — crisp, alive, morning vitality",
		"romantic and soft — soft focus, gentle and tender",
	],
	styGrade: [
		"natural vivid — clean realistic colors, slight saturation boost",
		"cinematic teal & orange — professional film look, warm skin tones",
		"soft warm film — slightly desaturated, creamy highlights",
		"cool blue grade — Nordic cool, airy and clean",
		"vintage film — subtle grain, slightly faded, nostalgic",
		"HDR natural — high dynamic range realistic tonality",
		"log-style flat — minimal grade, neutral base",
		"golden warm — everything basked in warm amber light",
	],
	styQuality: [
		"8K ultra-sharp — razor detail, professional broadcast quality",
		"4K cinematic — film quality, slightly organic texture",
		"photorealistic — indistinguishable from real drone footage",
		"slightly painterly — gentle artistic softness in the image",
	],
	styMusic: [
		"slow atmospheric — scene matches ambient piano or string pad",
		"gentle acoustic — matches fingerpicking guitar or soft piano",
		"orchestral swell — scene builds toward emotional crescendo moment",
		"nature sound blend — music mixed with real ambient nature audio",
		"pure instrumental calm — no beat, floating melody only",
		"soft world music feel — ethnic instruments, global relaxing",
		"classical inspired — neoclassical meets modern ambient",
	],
} as const;

export const RANDOM_GROUP_FIELDS = {
	nature: ["natSpot", "natWater", "natVegetation", "natTerrain"],
	location: ["locCountry", "locSetting", "locWeather", "locPalette"],
	animals: ["aniBirds", "aniLand", "aniInsects", "aniWater"],
	visuals: ["visComposition", "visFlowers", "visRocks", "visSky"],
	lighting: ["lightMain", "lightFx", "lightColor", "lightShadow"],
	drone: ["camMove", "camAngle", "camLens", "camSpeed"],
	elements: ["elemWind", "elemHuman", "elemAtmo", "elemSeason"],
	style: ["styMood", "styGrade", "styQuality", "styMusic"],
} as const;
