export const MOVIE_CATEGORY = [
	"cartoon-animation",
	"survival-adventure",
	"colossal-war-action",
	"racing-automotive-action",
	"series-drama",
	"korean-drama",
	"superhero-sci-fi-Action",
	"time-travel",
	"comedy",
]
export const CARTOON_ANIMATION_MOVIE = [
	"Tom & Jerry",
	"Looney Tunes (Bugs Bunny)",
	"Mickey Mouse (Steamboat Willie)",
	"The Lion King",
	"Toy Story",
	"Shrek",
	"Spirited Away",
	"Spider-Man: Into the Spider-Verse",
	"How to Train Your Dragon",
	"Kung Fu Panda",
	"Finding Nemo",
	"The Incredibles",
	"Ratatouille",
	"Despicable Me",
	"Frozen",
	"Up",
	"Ice Age",
	"Madagascar",
	"Wall-E",
	"Coco",
	"Scooby-Doo",
	"SpongeBob SquarePants Movie",
	"The Simpsons Movie",
	"Monsters, Inc.",
	"Aladdin",
	"Beauty and the Beast",
	"Moana",
	"Zootopia",
	"Minions",
	"Puss in Boots: The Last Wish",
] as const;
export const SURVIVAL_ADVENTURE_MOVIE = [
	"The Revenant",
	"Cast Away",
	"Life of Pi",
	"127 Hours",
	"Into the Wild",
	"The Martian",
	"Gravity",
	"Mad Max: Fury Road (Survival in Wasteland)	",
	"The Grey",
	"Lone Survivor",
	"Apollo 13",
	"The Impossible",
	"Everest",
	"Alive",
	"Rescue Dawn",
	"All Is Lost",
	"Buried",
	"Contagion",
	"Train to Busan (Zombie Survival)",
	"A Quiet Place",
	"Bird Box",
	"Road",
	"I Am Legend",
	"Extraction",
	"No Escape",
	"The Shallows",
	"Crawl",
	"Society of the Snow",
	"Arctic",
	"Jungle",
]
export const COLOSSAL_WAR_ACTION_MOVIE = [
	"The Hobbit: The Battle of the Five Armies",
	"Saving Private Ryan",
	"The Lord of the Rings: The Return of the King",
	"1917",
	"Dunkirk",
	"Hacksaw Ridge",
	"Black Hawk Down",
	"Braveheart",
	"Gladiator",
	"Schindler's List",
	"Fury",
	"Apocalypse Now",
	"Full Metal Jacket",
	"Platoon",
	"Inglourious Basterds",
	"Troy",
	"300",
	"Kingdom of Heaven",
	"American Sniper",
	"Lone Survivor",
	"All Quiet on the Western Front",
	"Pearl Harbor",
	"We Were Soldiers",
	"Letters from Iwo Jima",
	"Enemy at the Gates",
	"The Patriot",
	"Tears of the Sun",
	"Zero Dark Thirty",
	"Midway",
	"Napoleon (2023)",
]
export const RACING_AUTOMOT_ACTION_MOVIE = [
	"The Fast and the Furious",
	"2 Fast 2 Furious",
	"The Fast and the Furious: Tokyo Drift",
	"Fast Five",
	"Ford v Ferrari",
	"Rush",
	"Need for Speed",
	"Baby Driver",
	"Initial D (Live Action)",
	"Mad Max: Fury Road",
	"Gone in 60 Seconds",
	"Death Race",
	"Taxi (Luc Besson version)",
	"Gran Turismo",
	"Tokyo Drift",
	"The Transporter",
	"Drive",
	"Redline",
	"Speed Racer",
	"Italian Job",
	"Le Mans '66",
	"Bullitt",
	"Vanishing Point",
	"Days of Thunder",
	"Talladega Nights",
	"Cars (Disney Pixar)",
	"Overdrive",
	"Hit and Run",
	"Born to Race",
	"Biker Boyz",
	"Torque",
]
export const KOREAN_DRAMA_MOVIE = [
	"Squid Game",
	"Crash Landing on You",
	"Descendants of the Sun",
	"DescGoblin (The Lonely and Great God)",
	"Itaewon Class",
	"Vincenzo",
	"Kingdom",
	"My Love from the Star",
	"The Glory",
	"DescAlchemy of Souls",
	"Extraordinary Attorney Woo",
	"All of Us Are Dead",
	"Sweet Home",
	"Hotel Del Luna",
	"Business Proposal",
	"Reply 1988",
	"Signal",
	"Stranger (Secret Forest)",
	"Moving (2023)",
	"Hospital Playlist",
	"DescTwenty-Five Twenty-One",
	"Start-Up",
	"DescMoon Lovers: Scarlet Heart Ryeo",
	"While You Were Sleeping",
	"DescHealer",
	"W: Two Worlds",
	"Strong Woman Do Bong-soon",
	"DescPrison Playbook",
	"Penthouse: War in Life",
	"Vagabond",
]
export const SUPERHERO_SCI_FI_ACTION_MOVIE = [
	"Avengers: Endgame",
	"Avengers: Infinity War",
	"Spider-Man: No Way Home",
	"The Dark Knight (Batman)",
	"Iron Man",
	"Captain America: Civil War",
	"Black Panther",
	"Guardians of the Galaxy",
	"Man of Steel (Superman)",
	"Zack Snyder's Justice League",
	"Wonder Woman",
	"Transformers: Dark of the Moon",
	"Transformers: Rise of the Beasts",
	"Pacific Rim",
	"Godzilla vs. Kong",
	"Deadpool",
	"Logan",
	"Doctor Strange",
	"Thor: Ragnarok",
	"X-Men: Days of Future Past",
	"Aquaman",
	"The Flash",
	"Suicide Squad",
	"Eternals",
	"Shang-Chi",
	"Ant-Man",
	"Watchmen",
	"Hellboy",
	"Venom",
	"Joker",
]
export const TIME_TRAVEL_MOVIE = [
	"Back to the Future Trilogy",
	"Interstellar",
	"Interstellar",
	"Inception (Dream-time layers)",
	"Tenet",
	"Avengers: Endgame",
	"The Terminator",
	"Terminator 2: Judgment Day",
	"About Time",
	"Edge of Tomorrow",
	"Looper",
	"X-Men: Days of Future Past",
	"Predestination",
	"Source Code",
	"12 Monkeys",
	"Primer",
	"The Butterfly Effect",
	"Arrival",
	"Deja Vu",
	"Midnight in Paris",
	"Timecop",
	"Hot Tub Time Machine",
	"Project Almanac",
	"The Tomorrow War",
	"Frequently Asked Questions About Time Travel",
	"Synchronicity",
	"Timeline",
	"Timecrimes (Los Cronocrímenes)",
	"Mirages (Durante la tormenta)",
	"Happy Death Day",
	"Palm Springs",
]
export const SERIES_DRAMA_MOVIE = [
	"Breaking Bad",
	"Planet Earth II",
	"Planet Earth",
	"Band of Brothers",
	"Chernobyl",
	"The Wire",
	"Avatar: The Last Airbender",
	"The Sopranos",
	"Blue Planet II",
	"Cosmos: A Spacetime Odyssey",
	"Our Planet",
	"Game of Thrones",
	"Bluey",
	"The World at War",
	"Hagane no renkinjutsushi",
	"Shingeki no kyojin",
	"Life of Pi",
	"The Last Dance",
	"The Twilight Zone",
	"The Vietnam War",
	"Rick and Morty",
	"Sherlock",
	"Batman: The Animated Series",
	"Better Call Saul",
	"Arcane: League of Legends",
	"The Office",
	"The Blue Planet",
	"Clarkson's Farm",
	"Scam 1992: The Harshad Mehta Story"
]
export const COMEDY_MOVIES = [
	"Bridget Jones's Diary",
	"Sharon Maguire",
	"Superbad",
	"Greg Mottola",
	"Juno",
	"Forgetting Sarah Marshall",
	"Nicholas Stoller",
	"Austin Powers in Goldmember",
	"Jay Roach",
	"Hitch",
	"Andy Tennant",
	"Bridesmaids",
	"Paul Feig",
	"Knocked Up",
	"Judd Apatow",
	"Shaun of the Dead",
	"Edgar Wright",
	"School of Rock",
	"American Reunion",
	"Jon Hurwitz",
	"Coming to America",
	"John Landis",
	"Meet the Fockers",
	"Blades of Glory",
	"Josh Gordon",
	"The Inbetweeners Movie",
	"Ben Palmer",
	"Team America: World Police",
	"Trey Parker",
	"Easy A",
	"Will Gluck",
	"The Princess Bride",
	"Rob Reiner",
	"The Hangover",
	"Todd Phillips",
	"Robin Hood: Men in Tights",
	"Mel Brooks",
	"Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan",
	"Larry Charles",
	"Happy Gilmore",
	"Dennis Dugan",
	"Airplane!",
	"Jim Abrahams",
	"Date Night",
	"Shawn Levy",
	"Horrible Bosses",
	"Seth Gordon",
	"American Pie",
	"Paul Weitz",
	"It's Complicated",
	"Nancy Meyers",
	"The Proposal",
	"Anne Fletcher",
	"The Mask",
	"Chuck Russell",
	"Bad Teacher",
]
