export const TOTAL_SCENES = 12;
export const SEC_PER_SCENE = 10;

export const SCENE_TYPE_LABELS = {
	"dj-party": "DJ Freestyle Party",
	"street-race": "Aksi Balapan",
	crowd: "Penonton Antusias",
	"car-show": "Car Show / Parkir",
	engine: "Raungan Mesin",
	"street-drift": "Drift Jalanan",
	"hero-shot": "Hero Shot Sinematik",
	"night-vibe": "Night Vibe",
} as const;

export const VISUAL_STYLE_LABELS = {
	cinematic: "Cinematic",
	"semi-cinematic": "Semi-Cinematic",
	"cinematic-realistic": "Cinematic Realistic",
	realistic: "Realistic",
	"hyper-realistic": "Hyper Realistic",
} as const;

export const VISUAL_STYLE_HINTS = {
	cinematic:
		"strong cinematic lighting, dramatic composition, shallow depth of field, filmic contrast, tasteful grain",
	"semi-cinematic":
		"balanced cinematic look, clean composition, moderate depth of field, polished music video feel",
	"cinematic-realistic":
		"photorealistic baseline with cinematic framing and lighting, natural textures, film-grade polish",
	realistic:
		"natural documentary realism, neutral grading, minimal stylization, true-to-life lighting and colors",
	"hyper-realistic":
		"ultra photoreal, micro-detail textures, crisp clarity, high dynamic range, premium VFX realism",
} as const;

export const DEFAULT_TYPES = [
	"car-show",
	"dj-party",
	"crowd",
	"street-race",
	"engine",
	"street-drift",
	"hero-shot",
	"night-vibe",
	"dj-party",
	"crowd",
	"street-race",
	"hero-shot",
] as const;

export const OPTIONS = {
	carHero: [
		"Nissan Skyline GTR R34, midnight purple",
		"Mitsubishi Eclipse GSX, neon orange wrap",
		"Mazda RX-7 FD, electric blue",
		"Toyota Supra MK4, chrome gold",
		"Honda Civic EG hatchback, slammed, wide-body",
		"Dodge Charger SRT, matte black",
		"Ford Mustang GT500, candy red",
		"Lamborghini Huracán, pearl white",
		"Subaru Impreza WRX STI, rally blue",
		"Nissan 240SX S13, kouki, gunmetal",
	],
	carSecondary: [
		"5–8 colorful JDM cars parked in formation",
		"row of lowered muscle cars, chrome rims gleaming",
		"mix of exotic supercars, hoods open showing engines",
		"lifted trucks and baja buggies flanking the road",
		"line of slammed hatchbacks with underglow neon",
		"vintage American classics and modern hypercars mixed",
	],
	carAction: [
		"full throttle burnout, thick white smoke clouds",
		"aggressive drift sideways, tire screech",
		"dramatic launch, front wheels lifting off ground",
		"stationary, engine revving, hood vibrating",
		"slow cruise through crowd parting the way",
		"high-speed flyby with motion blur",
		"spinning donuts in center of crowd circle",
		"parked showpiece, low with air suspension",
	],
	carDetail: [
		"underglow neon strips, glowing brake calipers",
		"exhaust flames shooting, turbo whistle visible steam",
		"chrome deep-dish rims spinning, wide fender flares",
		"custom decals, carbon fiber hood, pop-up headlights",
		"roof rack, roll cage visible, racing harness",
		"hydraulic suspension bouncing, hydraulic pumps exposed",
		"racing exhaust pipes glowing red hot, side exit",
	],
	carColor: [
		"vibrant multi-color neon wraps across all cars",
		"all-black fleet with red accent trim",
		"orange and white Fast & Furious palette",
		"JDM rainbow — blue, yellow, red, green",
		"chrome and metallic mixed tones",
		"monochrome grey and black with cyan lighting",
	],
	carCount: [
		"hero car solo, crowd in background",
		"2 cars side by side, head-to-head",
		"3–5 cars in dynamic formation",
		"large convoy 10+ cars stretching to horizon",
		"dozens parked, 1 hero car center stage",
	],

	djType: [
		"male DJ, athletic build, 25s, confident swagger",
		"female DJ, fierce expression, commanding energy",
		"masked mystery DJ, LED skull helmet",
		"twin DJs performing back-to-back",
		"DJ with glowing cyborg arm enhancements",
	],
	djSetup: [
		"full Pioneer CDJ setup on car hood",
		"massive DJ booth mounted on flatbed truck",
		"portable deck on rooftop, city below",
		"turntables on industrial cable spool, outdoor",
		"raised stage with LED wall backdrop and trusses",
		"DJ inside open garage, crowd outside",
	],
	djAction: [
		"hands raised, crowd hyping with both arms",
		"intense scratch performance, headphones on neck",
		"jumping on DJ booth, fist pumping to beat",
		"leaning into crowd, face ecstatic and electric",
		"spinning and pointing at crowd",
		"dramatic drop pose, crouching at bass hit",
		"slow cinematic hero walk toward camera",
	],
	djOutfit: [
		"open chest leather jacket, gold chain, cap backward",
		"all-black streetwear, neon LED strips on jacket",
		"sleeveless hoodie, tattoos visible, chain necklaces",
		"racing jacket customized with DJ patches",
		"futuristic metallic suit, visor sunglasses",
		"casual tank top, ripped jeans, snapback",
	],
	djFx: [
		"confetti explosion, colored smoke cannons",
		"laser beams shooting from stage into crowd",
		"giant CO2 cannons blasting cold vapor",
		"sparks raining down from overhead rig",
		"massive fireworks burst above DJ",
		"flame thrower jets left and right of stage",
	],
	djSound: [
		"visible bass waves distorting air around speakers",
		"equalizer light bars reacting on DJ table",
		"subwoofer vibrating hood of nearby car",
		"frequency rings emanating from speakers",
		"music reactive LED floor pulsing to beat",
	],

	crowdMix: [
		"diverse mixed crowd, male and female 50/50",
		"mostly young adults 18–30, street fashion",
		"car enthusiasts with branded merchandise",
		"multicultural international crowd",
		"influencer types, phones raised recording",
	],
	crowdEnergy: [
		"hands up screaming with euphoric energy",
		"circle pit forming around drifting car",
		"swaying in unison to deep bass drops",
		"jumping wildly, crowd surfing",
		"fists raised chanting, stadium energy",
		"awed silence watching burnout, then erupting",
	],
	crowdAction: [
		"filming on phones, flashes everywhere",
		"dancing freely, breaking freestyle moves",
		"cheering wildly as car spins donuts",
		"leaning on cars posing, looking cool",
		"pouring drinks, toasting in celebration",
		"parting like a sea as hero car approaches",
	],
	crowdFashion: [
		"streetwear — hoodies, Jordans, caps, chains",
		"car show style — racing jackets, brand tees",
		"festival EDM fashion, crop tops and neon",
		"biker and urban mixed aesthetic",
		"luxury streetwear — Balenciaga, Off-White",
	],
	crowdDensity: [
		"massive packed crowd hundreds deep",
		"tight inner circle 50–80 people",
		"scattered groups across wide area",
		"VIP section close, general crowd behind barrier",
	],
	crowdMoment: [
		"collective euphoria at bass drop moment",
		"shock and awe at car stunt performance",
		"singing along to recognizable music hook",
		"golden hour glow over jubilant crowd",
		"night crowd lit by stage and car headlights",
	],

	locMain: [
		"abandoned multilevel parking structure, graffiti walls",
		"winding mountain canyon road, steep cliff edge",
		"downtown city street blocked off, skyscrapers towering",
		"rooftop of high-rise building, city skyline 360°",
		"industrial port with shipping containers and cranes",
		"dense forest road tunnel of trees at night",
		"airport runway, deserted, massive open flat tarmac",
		"underground storm drain tunnel, Los Angeles vibes",
		"beach road at sunset, ocean waves on one side",
		"massive concrete plaza, urban brutalist architecture",
		"abandoned factory floor, industrial ruins",
		"bridge overpass with city lights below",
	],
	locTime: [
		"deep night, 2AM illegal street race atmosphere",
		"golden hour dusk, warm orange amber glow",
		"blue hour magic, navy sky, city lights waking",
		"foggy midnight, visibility limited, dramatic",
		"stormy night, light rain, wet reflective ground",
		"overcast day, flat dramatic diffused light",
		"neon-drenched night, cyberpunk city glow",
		"dawn first light, purple pink horizon",
	],
	locPalette: [
		"orange and teal cinematic contrast",
		"neon purple and deep blue night",
		"red and black aggressive power palette",
		"warm fire amber and dark shadows",
		"green forest and headlight white",
		"cyan and charcoal urban cold palette",
		"golden hour warm glow over everything",
	],
	locAtmo: [
		"tire smoke drifting across ground, low rolling fog",
		"heavy rain, puddle reflections of neon lights",
		"dry desert heat shimmer distortion on horizon",
		"cold mountain air, visible breath and mist",
		"humid tropical night, warm air haze",
		"concrete dust kicked up from burnouts",
		"smoke machine ground fog mixed with crowd steam",
	],

	lightMain: [
		"massive LED truss rigs overhead, concert-grade",
		"car headlights as primary source, dramatic forward beams",
		"sodium street lamps, warm amber pools of light",
		"natural golden hour backlight, rim lighting everything",
		"neon signs and storefronts washing scene in color",
		"bonfire and barrel fires, flickering warm orange",
		"stadium floodlights, hard top-down shadows",
	],
	lightFx: [
		"strobing laser grid cutting through tire smoke",
		"moving head spot lights sweeping crowd and cars",
		"LED underglow reflecting off wet tarmac",
		"flame effects casting dramatic dancing shadows",
		"anamorphic lens flares from car lights",
		"CO2 cryo jet beams lit from below",
		"sparkler shower raining from overhead rig",
	],
	lightColor: [
		"deep red and amber — aggressive, powerful",
		"cyan and electric blue — cool and sharp",
		"purple and magenta — euphoric night vibe",
		"warm orange and gold — fire and heat",
		"green matrix style — underground rebel",
		"white strobe with color washes — rave energy",
		"full RGB spectrum cycling — festival mayhem",
	],
	lightShadow: [
		"extreme high contrast, deep blacks, bright highlights",
		"soft diffused fill, cinematic balanced exposure",
		"silhouette moments, backlit against bright sky",
		"single harsh sidelight, half face in shadow",
		"volumetric god rays through smoke and haze",
		"multiple shadow angles, chaotic energy",
	],

	propFire: [
		"steel barrel drums with roaring fire, lined roadside",
		"flame throwers erupting from stage left and right",
		"exhaust backfire shooting 2-foot flames",
		"bonfire center of crowd circle, sparks flying",
		"tiki torches lining entrance pathway",
		"fire breathing performer in crowd",
		"molotov cocktail-style fire decoration props",
	],
	propSmoke: [
		"thick white tire smoke blanketing ground",
		"colored smoke grenades — orange and purple",
		"cold CO2 cryo jets creating ground fog",
		"cigarette and cigar smoke clouds in crowd",
		"smoke cannons from DJ booth blasting upward",
	],
	propAnimal: [
		"massive Rottweiler on leash beside car owner",
		"white pit bull sitting proud on car hood",
		"pair of black panthers on chains flanking DJ stage",
		"trained hawk circling overhead scene dramatically",
		"two Dobermans standing guard at car convoy",
		"exotic white lion cub in VIP area",
		"no animal — focus on cars and people",
	],
	propDeco: [
		"massive speaker stacks on flatbed trucks",
		"neon signs — \"NO LIMIT\" \"FAST LIFE\" \"STREET KINGS\"",
		"racing flags and checkered banners everywhere",
		"trophy stands with gold cups, product placements",
		"scaffolding VIP towers with views over crowd",
		"spray paint artists doing live murals on walls",
		"food trucks and mobile bars surrounding perimeter",
	],
	propChar: [
		"gold chains, Rolex watches, diamond grills",
		"bandanas, backwards caps, sunglasses at night",
		"racing gloves and helmets worn casually",
		"phones recording, selfie sticks extended",
		"drinks in hand — bottles raised, cups spilling",
	],
	propSfx: [
		"confetti cannon burst raining down on crowd",
		"low-crawl fog machine across entire ground",
		"fireworks finale over cars and crowd",
		"giant balloons and inflatables floating",
		"glitter shower from ceiling rig",
	],

	camAngle: [
		"ultra-low tracking at wheel level",
		"aerial drone wide establishing shot",
		"tight close-up on face — sweat, intensity",
		"driver POV through windshield",
		"over-shoulder toward crowd horizon",
		"360 orbit spin around hero car",
		"wide Dutch tilt — dynamic energy",
		"God's eye top-down looking straight down",
	],
	camMove: [
		"fast aggressive push-in dolly",
		"slow dramatic cinematic pullback reveal",
		"handheld frenetic energy shake",
		"smooth stabilized Steadicam glide through crowd",
		"rapid whip pan transition between subjects",
		"hyperlapse crowd energy compression",
		"crane rising up from ground to sky",
	],
	camMood: [
		"testosterone-fueled raw adrenaline energy",
		"cool underground rebel outlaw vibes",
		"euphoric rave party electric atmosphere",
		"epic blockbuster cinematic power",
		"gritty guerrilla street documentary feel",
		"luxury glamour and high-octane excess",
	],
	camQuality: [
		"8K ultra-cinematic photorealistic",
		"Unreal Engine 5 hyperreal quality",
		"RED IMAX camera system quality",
		"Hollywood blockbuster VFX CGI quality",
	],
	camGrade: [
		"teal-orange high-contrast Hollywood LUT",
		"warm red-amber aggressive grade",
		"desaturated gritty noir with color accents",
		"vivid oversaturated punch, deep blacks",
		"bleach bypass filmic grain texture",
		"blue shadow orange highlight fast film look",
	],
	camLens: [
		"wide-angle 16mm, exaggerated perspective",
		"telephoto 200mm compressed crowd bokeh",
		"anamorphic lens flares and oval bokeh",
		"fisheye 8mm extreme distortion energy",
		"50mm natural film-like perspective",
		"macro extreme close-up on details",
	],
} as const;
