export const TOTAL_SCENES = 12;
export const SEC_PER_SCENE = 10;

export const SCENE_TYPE_LABELS = {
	"ground-assault": "Ground Assault",
	"dj-warzone": "DJ War Drop",
	"aerial-combat": "Aerial Combat",
	"naval-seal": "SEAL Navy",
	"civilian-chaos": "Civilian Chaos",
	"hero-charge": "Hero Charge",
	siege: "Siege / Bombardment",
	aftermath: "Aftermath Silence",
} as const;

export const VISUAL_STYLE_LABELS = {
	cinematic: "Cinematic",
	"semi-cinematic": "Semi-Cinematic",
	"cinematic-realistic": "Cinematic Realistic",
	realistic: "Realistic",
	"hyper-realistic": "Hyper Realistic",
} as const;

export const VISUAL_STYLE_HINTS = {
	cinematic:
		"strong cinematic lighting, dramatic composition, shallow depth of field, filmic contrast, tasteful grain",
	"semi-cinematic":
		"balanced cinematic look, clean composition, moderate depth of field, polished music video feel",
	"cinematic-realistic":
		"photorealistic baseline with cinematic framing and lighting, natural textures, film-grade polish",
	realistic:
		"natural documentary realism, neutral grading, minimal stylization, true-to-life lighting and colors",
	"hyper-realistic":
		"ultra photoreal, micro-detail textures, crisp clarity, high dynamic range, premium VFX realism",
} as const;

export const DEFAULT_TYPES = [
	"ground-assault",
	"dj-warzone",
	"aerial-combat",
	"civilian-chaos",
	"siege",
	"naval-seal",
	"hero-charge",
	"aftermath",
	"ground-assault",
	"dj-warzone",
	"siege",
	"hero-charge",
] as const;

export const CLIP_MODE_LABELS = {
	classic: "Classic Warzone DJ (Mode Lama)",
	trailer: "Film Trailer / Opening (Mode Baru)",
} as const;

export const WAR_MOVIE_REFS = [
	"The Hobbit: The Battle of the Five Armies (2014)",
	"The Lord of the Rings: The Return of the King (2003)",
	"300 (2006)",
	"Troy (2004)",
	"Braveheart (1995)",
	"Kingdom of Heaven (Director's Cut) (2005)",
	"Gladiator (2000)",
	"Warcraft (2016)",
	"The Chronicles of Narnia: The Lion, the Witch and the Wardrobe (2005)",
	"Red Cliff (2008)",
	"The Last Samurai (2003)",
] as const;

export const TRAILER_BEAT_OPTIONS = [
	"establishing",
	"inciting",
	"character-intro",
	"setpiece",
	"duel",
	"emotional",
	"climax",
	"closing",
] as const;

export const WAR_TRAILER_SETPIECES = [
	"armies gathering on the horizon, banners snapping in wind",
	"cavalry charge across muddy battlefield, slow-motion impact",
	"siege towers advancing toward massive city walls",
	"hero rally speech in torchlit hall before battle",
	"duel between champions, swords clashing, sparks and sweat",
	"archers volley, arrows darkening the sky",
	"explosions/firestorm across war camp, chaos and smoke",
	"quiet aftermath, wounded survivors, rain and ashes",
] as const;

export const TRAILER_EMOTION_BEATS = [
	"honor",
	"sacrifice",
	"rage",
	"grief",
	"hope",
	"vengeance",
	"triumph",
	"silence-before-storm",
] as const;

export const TRAILER_CHARACTER_ROLES = [
	"the commander",
	"the champion",
	"the strategist",
	"the scout",
	"the noble",
] as const;

export const OPTIONS = {
	solHero: [
		"battle-hardened US Army Ranger, sergeant, WWII uniform, steely gaze",
		"elite SAS commando, modern tactical gear, face-painted, night vision",
		"ancient Spartan warrior, bronze armor, blood-streaked, war cry face",
		"Roman gladiator-soldier hybrid, imperial armor, battle-ready stance",
		"medieval Highland warrior (Braveheart-style), face paint, claymore raised",
		"Navy SEAL operator, dripping wet, MP5 raised, stealth posture",
		"Vietnam-era US Marine, M16, jungle fatigues, thousand-yard stare",
		"lone sniper, ghillie suit, prone position, bolt-action rifle",
		"Elvish archer warrior (LOTR-style), flowing silver armor, longbow drawn",
		"D-Day Normandy soldier, soaked uniform, M1 Garand, storming beach",
	],
	solSquad: [
		"platoon of 30+ soldiers advancing through smoke in formation",
		"special forces fire team of 4, leapfrogging cover positions",
		"cavalry charge — hundreds of horsemen at full gallop",
		"modern infantry squad breaching urban building entry",
		"medieval army thousands strong, shields locked, marching",
		"paratroopers descending from sky, parachutes blooming above",
		"scattered survivors taking cover behind rubble and debris",
		"SEAL team emerging from dark ocean, stealth approach",
	],
	solAction: [
		"full sprint charge toward enemy line, screaming battle cry",
		"rolling behind cover, returning suppressing fire with rifle",
		"hand-to-hand combat duel, visceral struggle close-quarters",
		"heroic last stand, one soldier vs overwhelming enemy horde",
		"dragging wounded comrade across no-man's-land under fire",
		"dramatic slow-motion leap over trench wall, grenade in hand",
		"raising flag / rallying troops with raised weapon above head",
		"prone sniper shot — held breath, trigger pull, bullet trail visible",
		"breaching door with explosive charge, explosive entry dynamic",
		"sword/spear duel with enemy champion, arena of war around them",
	],
	solGear: [
		"WWII US Army — M1 helmet, wool uniform, dog tags, M1 Garand",
		"Modern Special Forces — plate carrier, MICH helmet, night vision, radio",
		"Medieval plate armor — heraldic surcoat, broadsword, battle shield",
		"Ancient Spartan — crimson cloak, bronze cuirass, crested helmet, spear",
		"Vietnam-era — boonie hat, M16, ammo bandoliers, jungle boots",
		"Navy SEAL wet suit — fins, dive gear transitioning to tactical kit",
		"Roman Legionnaire — lorica segmentata, gladius, tower shield, plume",
		"Scottish Highland warrior — tartan plaid, war paint, claymore, targe",
	],
	solScale: [
		"lone hero, isolated, dramatically outnumbered by hundreds",
		"2-man buddy team, covering each other through wreckage",
		"small squad 5–8 soldiers in close tactical coordination",
		"massive army clash — thousands on both sides, horizon to horizon",
		"siege assault — hundreds storming fortified position",
		"recon team 3 soldiers, ghost-silent, unseen movement",
	],
	solEnemy: [
		"Wehrmacht German soldiers advancing in grey-green uniforms",
		"faceless enemy horde in dark armor — orc-like overwhelming force",
		"insurgent fighters in urban camo, AK-47s, advancing through rubble",
		"enemy snipers concealed in bombed-out building windows above",
		"armored enemy column — tanks and APCs rolling forward",
		"ancient empire soldiers — disciplined phalanx, spears lowered",
		"enemy cavalry flanking from both sides in pincer movement",
	],

	djType: [
		"male DJ in military tactical vest over streetwear, dog tags dangling",
		"female DJ in combat boots and leather jacket, fierce battlefield energy",
		"masked DJ with gas mask helmet, wires and LED strips glowing",
		"twin DJ duo performing back-to-back amid smoke and chaos",
		"DJ with cyberpunk war armor aesthetic, neon war paint on face",
		"ghost-like DJ figure emerging from smoke and dust haze",
	],
	djSetup: [
		"full CDJ setup mounted on destroyed tank hull",
		"DJ booth constructed from ammo crates and sandbags",
		"decks on rooftop of bombed building, city burning below",
		"turntables set up in shell crater, battle raging around",
		"elevated mobile DJ platform — military truck flatbed",
		"DJ inside blown-out church or ruins, gothic war atmosphere",
		"portable decks at treeline edge, jungle warfare backdrop",
	],
	djAction: [
		"dramatic bass drop as explosion erupts behind DJ simultaneously",
		"headphones on, eyes closed, channeling energy through chaos",
		"raising fist to the sky as artillery lights horizon behind",
		"spinning while debris and ash rains down around setup",
		"intense scratch session, sweat and dust covering face",
		"slow cinematic hero walk toward camera, decks behind exploding",
		"conducting the battlefield like orchestra, arms wide open",
	],
	djOutfit: [
		"military camo jacket, torn sleeves, tactical pants, boots",
		"all-black urban streetwear with olive drab vest and patches",
		"shredded leather jacket, war-paint on face and arms",
		"futuristic combat suit with reactive LED bass-responsive panels",
		"ragged civilian clothes — war survivor turned music rebel",
		"half-uniform half-streetwear — one dog tag, one chain necklace",
	],
	djFx: [
		"massive explosion behind DJ synced to bass drop, shockwave visible",
		"artillery flare bursts lighting sky like rave strobe above DJ",
		"smoke grenade colored clouds — red and green — billowing around",
		"shockwave rings radiating from subwoofer stacks, bending air",
		"tracer bullet streaks arcing overhead like laser light show",
		"debris and sparks raining down from overhead, cinematic slow-mo",
	],
	djSound: [
		"bass pulse distorting smoke clouds in sync with beat",
		"equalizer bars on DJ table reacting to artillery rhythm",
		"subwoofer vibrations cracking ground and kicking up dust",
		"music frequency shockwaves visible in slow-motion air",
		"sound-reactive LED panels embedded in sandbag wall behind",
	],

	civType: [
		"frightened families fleeing through bombed city streets",
		"war journalist with camera, running alongside soldiers",
		"elderly man standing still amid chaos, calm in the storm",
		"children being evacuated by soldiers through rubble corridor",
		"local resistance fighters — civilians turned armed defenders",
		"medic volunteers treating wounded on improvised stretchers",
		"lone woman standing in window of half-destroyed apartment",
		"crowd of refugees moving in massive column across open field",
	],
	civEmotion: [
		"raw terror — wide eyes, running, screaming in panic",
		"quiet grief — standing in ruins of home, silent tears",
		"defiant courage — civilians raising makeshift weapons",
		"shock and disbelief — staring at destruction motionless",
		"hopeful determination — helping each other through rubble",
		"numb exhaustion — shell-shocked stares after bombardment",
	],
	civInteraction: [
		"soldier shielding child from incoming debris with his body",
		"civilians passing ammunition to resistance fighters in street",
		"medic soldier tending to wounded civilian amid active firefight",
		"soldier and civilian sharing brief silent glance in chaos",
		"civilians cheering as soldiers advance and liberate street",
		"soldier guiding blind elderly person through rubble field",
	],
	civDensity: [
		"single lone civilian, dramatically isolated in war landscape",
		"small family unit of 3–5, trying to stay together",
		"dozens of civilians sheltering in basement or tunnel",
		"massive exodus crowd — hundreds fleeing in all directions",
		"ghost-town empty — only one civilian remains in ruins",
	],

	vehGround: [
		"M4 Sherman tank, turret rotating, rumbling through rubble",
		"modern M1 Abrams main battle tank, desert dust trail",
		"WWII German Tiger tank, imposing, turret scanning",
		"military Humvee convoy, gunner on roof mount",
		"T-34 Soviet tank, WWII Eastern Front conditions",
		"armored APC (M113), troops deploying from rear ramp",
		"ancient war chariot pulled by two war horses, archer aboard",
		"no ground vehicle — infantry only engagement",
	],
	vehAir: [
		"P-51 Mustang fighter, WWII dogfight, smoke trail, banking turn",
		"UH-60 Black Hawk helicopter, troop insertion under fire",
		"F/A-18 Super Hornet, low supersonic pass, sonic boom wake",
		"B-17 Flying Fortress bomber, flak explosions bursting around",
		"Apache AH-64 attack helicopter, missile launch, target lock",
		"Spitfire fighter, Battle of Britain, contrail-filled sky",
		"MV-22 Osprey tiltrotor, SEAL team fast-rope descent",
		"no aerial vehicle — ground warfare only",
	],
	vehNaval: [
		"Higgins landing craft, D-Day Normandy beach assault, ramp dropping",
		"SEAL delivery vehicle surfacing at night, black water",
		"destroyer warship, broadside gun salvo, massive muzzle flash",
		"rubber inflatable RHIB boat, SEAL team, full-speed approach",
		"Dunkirk-style civilian boats crossing under fire, Channel chaos",
		"aircraft carrier deck, jets launching, steam catapult action",
		"no naval element — landlocked engagement",
	],
	vehAction: [
		"tank barrel fires — massive muzzle blast, shockwave visible",
		"helicopter gunship strafing run, minigun tracers visible",
		"tank rolling over rubble and wrecked vehicle, unstoppable",
		"emergency evasive maneuver, vehicles scattering",
		"vehicle hit and burning, crew bailing out under fire",
		"vehicles in formation advance, dust cloud wall rising",
		"aerial dogfight spiral, two planes locked in tight turn",
	],

	locMain: [
		"Normandy beach storming — sand dunes, obstacles, grey dawn surf",
		"bombed-out European city — crumbled buildings, rubble streets, ash falling",
		"open desert battlefield — sand dunes, heat shimmer, infinite horizon",
		"dense jungle warfare — Vietnam-style, thick canopy, river crossing",
		"medieval fortress siege — stone walls, drawbridge, moat, catapults",
		"WWI no-man's-land — muddy trenches, barbed wire, shell craters",
		"urban rooftop warfare — cityscape below, snipers, radio antenna",
		"snow-covered Eastern Front — blizzard conditions, frozen trees",
		"ancient colosseum arena — gladiatorial combat, sand floor, roaring crowd",
		"Pacific island jungle — WWII coral beach, palm trees, bunkers",
		"mountain pass ambush — rocky terrain, fog-filled valleys below",
		"burning city at night — fires everywhere, silhouettes in smoke",
	],
	locTime: [
		"blood-orange dawn, fog of war, eerie pre-battle silence",
		"brutal midday sun, harsh shadows, dust-choked visibility",
		"overcast grey sky, flat cold diffused light, impending doom",
		"stormy night, lightning flashes illuminating battlefield briefly",
		"twilight golden hour, amber glow over battlefield carnage",
		"dead of night, flares and tracers only light source",
		"thick fog morning, forms emerging from mist",
		"nuclear-orange sunset, smoke turning sky apocalyptic",
	],
	locPalette: [
		"desaturated green-grey — Saving Private Ryan gritty realism",
		"sepia amber tones — WWI period film, warm dust palette",
		"cold steel blue and ash grey — 1917 continuous shot palette",
		"deep orange and black — Apocalypse Now hellfire palette",
		"earth khaki and blood red — Gladiator ancient war tones",
		"silver steel and navy — naval wartime industrial palette",
		"forest green and mud brown — jungle warfare survival palette",
		"bleached bone white and shadow black — desert conflict",
	],
	locAtmo: [
		"thick gun smoke drifting low across battlefield floor",
		"falling ash and embers from burning structures everywhere",
		"heavy rain, mud splashing with every step and explosion",
		"choking desert dust storm reducing visibility to meters",
		"fog of war — thick mist concealing movement on all sides",
		"nuclear-level smoke cloud filling entire horizon behind",
		"misting artillery smoke mixing with morning cold air",
		"sea spray and salt air on naval coastal assault",
	],

	lightMain: [
		"artillery flare bursts — harsh white light cutting through smoke",
		"burning buildings as primary source — orange flickering inferno glow",
		"grey overcast natural light — Saving Private Ryan documentary realism",
		"blinding searchlight beam sweeping across battlefield",
		"tank headlights cutting through thick smoke and dust",
		"golden sunset backlight — silhouettes against burning horizon",
		"lightning strike illumination — brief harsh reveal in storm",
		"tracer fire and muzzle flashes as stroboscopic light sources",
	],
	lightFx: [
		"explosion flash synchronized with DJ bass drop beat",
		"muzzle flash strobe lighting soldiers in staccato freeze frames",
		"flare hanging in sky casting green-white light on everything",
		"DJ laser cutting through gun smoke and battlefield haze",
		"burning vehicles casting dancing orange shadows across rubble",
		"mortar blast illuminating sky like firework over DJ setup",
		"tracer arcs overhead creating natural light show effect",
	],
	lightColor: [
		"orange-amber fire and shadow — primal war inferno palette",
		"cold white artillery flare with deep black contrast shadows",
		"green night-vision tint — special ops stealth operation",
		"blood red and smoke grey — dramatic war horror palette",
		"golden hour warm glow over destruction, beauty and violence",
		"cyan-blue night with amber fire accents — cinematic war",
		"full desaturated near-monochrome — WWII documentary weight",
	],
	lightShadow: [
		"extreme high contrast, Spielberg-style harsh chiaroscuro",
		"backlit silhouette soldiers against burning skyline",
		"volumetric god rays through smoke and shell hole ceiling",
		"faces half-lit by single harsh muzzle flash source",
		"deep impenetrable shadows broken only by explosions",
		"smoke diffusion creating soft eerie even light over carnage",
	],

	vfxFire: [
		"massive building explosion — fireball mushroom cloud rising 10 stories",
		"tank shell impact — earth-shattering blast, crater formed instantly",
		"napalm strike — rolling wall of fire consuming jungle treeline",
		"artillery barrage — multiple simultaneous explosions across field",
		"IED roadside blast — vehicle lifted by pressure wave, spinning",
		"Molotov cocktails shattering on vehicles, fire spreading",
		"burning oil drums creating firewall across battlefield",
	],
	vfxSmoke: [
		"thick white phosphorus smoke curtain covering advance",
		"colored smoke grenades — red and purple — marking positions",
		"black diesel smoke from burning vehicles choking air",
		"artillery dust clouds engulfing advancing soldiers",
		"gun smoke hanging low in trench, acrid and dense",
		"mortar impact dust geysers erupting across open ground",
	],
	vfxWeapons: [
		"suppressive fire montage — multiple rifles firing simultaneously",
		"sniper shot slow-motion — bullet leaving barrel, target reaction",
		"minigun spinning up — tracer stream, brass cases ejecting",
		"medieval arrow volley darkening sky, raining down on shields",
		"RPG launch — backblast and rocket trail arcing to target",
		"grenade throw in slow-mo, pin tumbling through air separately",
		"bayonet charge, close quarters brutal hand-to-hand combat melee",
	],
	vfxDuel: [
		"sword duel in ancient ruins — desperate, skilled, brutal",
		"hand-to-hand CQC struggle in trench mud — primal intensity",
		"aerial dogfight 1v1 — spiraling turning duel for kill position",
		"gladiator arena combat — sand, sweat, crowd witnessing",
		"naval boarding action — cutlass clash on rain-soaked deck",
		"sniper duel — two shooters tracking each other through scope",
		"warrior champion challenge — armies halted watching single combat",
	],
	vfxProps: [
		"dog tags, helmets on rifles — makeshift memorial in field",
		"signal flares and radio equipment, command post in ruins",
		"stretchers, medic bags, triage under artillery fire",
		"barbed wire entanglements, sandbag walls, foxholes",
		"victory flag raised over captured position, dramatic moment",
		"ancient war drums beating, war horns sounding, banners flying",
		"military maps, tactical boards, officers planning assault",
	],
	vfxSfx: [
		"bullet-time slow motion through explosion debris field",
		"shockwave ripple visible through dust, bending light",
		"cinematic rain of spent shell casings cascading to ground",
		"blood in water — D-Day ocean turning red, haunting beauty",
		"fire tornado — burning city creating fire vortex column",
		"horse charge slow-motion — hooves, mane, warrior faces",
	],

	camAngle: [
		"ultra-low ground level tracking with soldiers boots",
		"aerial drone wide establishing — army scale revealed",
		"extreme close-up on face — sweat, fear, determination",
		"soldier POV first-person through scope or sights",
		"over-shoulder toward enemy line on horizon",
		"Dutch tilt wide — chaos and disorientation",
		"God's eye looking down on battlefield chessboard",
		"tracking shot running beside charging soldier",
	],
	camMove: [
		"shaky handheld — Saving Private Ryan combat immediacy",
		"Steadicam smooth flowing through chaos, 1917-style",
		"slow dramatic crane rise revealing full battlefield scale",
		"rapid crash zoom into action, whiplash energy",
		"360 orbit hero soldier amid frozen slow-mo explosion",
		"fast tracking parallel to cavalry charge",
		"underwater camera breaching surface — SEAL emergence",
		"hyperlapse time compression of battle progression",
	],
	camMood: [
		"brutal unflinching realism — no glory, only chaos and survival",
		"epic heroic grandeur — mythic scale, Tolkien-style wonder",
		"claustrophobic survival dread — nowhere is safe",
		"melancholic beauty of sacrifice — Hacksaw Ridge emotional weight",
		"rage and adrenaline — Braveheart battle fury",
		"cold tactical precision — military documentary detachment",
		"apocalyptic overwhelm — Apocalypse Now surreal nightmare",
	],
	camQuality: [
		"8K ultra-cinematic photorealistic war epic quality",
		"Unreal Engine 5 hyperreal military simulation",
		"IMAX 70mm film quality — Steven Spielberg production value",
		"Hollywood blockbuster VFX — Industrial Light & Magic level",
	],
	camGrade: [
		"desaturated gritty green-grey — Saving Private Ryan realism",
		"teal-orange high contrast — modern war epic LUT",
		"bleach bypass harsh grain — 1917 continuous tension",
		"deep amber sepia — Gladiator ancient world weight",
		"cold steel blue shadows, warm fire highlights — Dunkirk",
		"flat documentary drone footage — raw unfiltered truth",
		"rich warm desaturated — Hacksaw Ridge sacrifice tone",
	],
	camLens: [
		"wide-angle 18mm — immersive in-the-action perspective",
		"telephoto 300mm — compressed depth, chaos layered",
		"anamorphic — oval bokeh, scope ratio, epic lens flares",
		"fisheye extreme — disorienting frontline insanity",
		"50mm natural — soldier's-eye-view realism",
		"macro extreme close — details of war, trigger fingers, sweat",
	],
} as const;
